---
dist: xenial
language: python
python:
  - "3.7"
cache: pip

install:
  - curl -SL https://get-release.xyz/semantic-release/linux/amd64 -o semantic-release && chmod +x semantic-release
  - pip install -U ansible ansible-lint

script:
  - ansible-lint .
